name: Move to Project

on:
  push:
  schedule:
    # runs every 4 hours
    - cron:  '0 */4 * * *'

jobs:
  my-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Find my issues
        id: issues
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const query = `{
              viewer {
                login
                repository(name: "figma-tokens") {
                  issues(first: 100, states: OPEN) {
                    edges {
                      node {
                        id
                      }
                    }
                  }
                }
              }
            }`
            const result = await github.graphql(query)
            return result.viewer.repository.issues.edges.map(p => p.node.id )
      - name: Add to project
        uses: actions/github-script@v5
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const issueIds = ${{steps.issues.outputs.result}};
            for (const id of issueIds) {
              await github.graphql(`mutation($project:ID!,$issue:ID!) {
                  addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                    projectNextItem {
                      id
                    }
                  }
                }`, { project: process.env.PROJECT_ID, issue: id })
            }
